//======================================================================================================================
// Actions
//======================================================================================================================
// Description:
// Const list of all Redux actions in app
//======================================================================================================================

export const

// Home

    // 20 Random Girl Names
    FETCH_NAMES_START_G = 'FETCH_NAMES_START_G',
    FETCH_NAMES_SUCCESS_G = 'FETCH_NAMES_SUCCESS_G',
    FETCH_NAMES_FAIL_G = 'FETCH_NAMES_FAIL_G',

    // 20 Random Boy Names
    FETCH_NAMES_START_B = 'FETCH_NAMES_START_B',
    FETCH_NAMES_SUCCESS_B = 'FETCH_NAMES_SUCCESS_B',
    FETCH_NAMES_FAIL_B = 'FETCH_NAMES_FAIL_B',

    // Random Name
    FETCH_RANDOM_START = 'FETCH_RANDOM_START',
    FETCH_RANDOM_SUCCESS = 'FETCH_RANDOM_SUCCESS',
    FETCH_RANDOM_FAIL = 'FETCH_RANDOM_FAIL',

    // Fresh Collections
    FETCH_H_COLLECTIONS_START = 'FETCH_H_COLLECTIONS_START',
    FETCH_H_COLLECTIONS_SUCCESS = 'FETCH_H_COLLECTIONS_SUCCESS',
    FETCH_H_COLLECTIONS_FAIL = 'FETCH_H_COLLECTIONS_FAIL',

// Explore

    // Explore Names
    FETCH_ALLNAMES_START = 'FETCH_ALLNAMES_START',
    FETCH_ALLNAMES_SUCCESS = 'FETCH_ALLNAMES_SUCCESS',
    FETCH_ALLNAMES_FAIL = 'FETCH_ALLNAMES_FAIL',

// Name

    // Name Info
    FETCH_NAMEINFO_START = 'FETCH_NAMEINFO_START',
    FETCH_NAMEINFO_SUCCESS = 'FETCH_NAMEINFO_SUCCESS',
    FETCH_NAMEINFO_FAIL = 'FETCH_NAMEINFO_FAIL',

    // Recent
    FETCH_RECENTHISTORY_START = 'FETCH_RECENTHISTORY_START',
    FETCH_RECENTHISTORY_SUCCESS = 'FETCH_RECENTHISTORY_SUCCESS',
    FETCH_RECENTHISTORY_FAIL = 'FETCH_RECENTHISTORY_FAIL',

    // Full History
    FETCH_HISTORY_START = 'FETCH_HISTORY_START',
    FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS',
    FETCH_HISTORY_FAIL = 'FETCH_HISTORY_FAIL',

    // Full History
    FETCH_VARIATIONS_START = 'FETCH_VARIATIONS_START',
    FETCH_VARIATIONS_SUCCESS = 'FETCH_VARIATIONS_SUCCESS',
    FETCH_VARIATIONS_FAIL = 'FETCH_VARIATIONS_FAIL',

    // Apple Songs
    FETCH_SONGS_START = 'FETCH_SONGS_START',
    FETCH_SONGS_SUCCESS = 'FETCH_SONGS_SUCCESS',
    FETCH_SONGS_FAIL = 'FETCH_SONGS_FAIL',

    // Trends
    FETCH_TRENDS_START = 'FETCH_TRENDS_START',
    FETCH_TRENDS_SUCCESS = 'FETCH_TRENDS_SUCCESS',
    FETCH_TRENDS_FAIL = 'FETCH_TRENDS_FAIL',


    // Origins
    FETCH_ORIGINS_START = 'FETCH_ORIGINS_START',
    FETCH_ORIGINS_SUCCESS = 'FETCH_ORIGINS_SUCCESS',
    FETCH_ORIGINS_FAIL = 'FETCH_ORIGINS_FAIL',

// Collection

    // Name Info
    FETCH_COLLECTION_START = 'FETCH_COLLECTION_START',
    FETCH_COLLECTION_SUCCESS = 'FETCH__COLLECTION_SUCCESS',
    FETCH_COLLECTION_FAIL = 'FETCH_COLLECTION_FAIL',

    // Collection Names
    FETCH_COLLECTIONNAMES_START = 'FETCH_COLLECTIONNAMES_START',
    FETCH_COLLECTIONNAMES_SUCCESS = 'FETCH__COLLECTIONNAMES_SUCCESS',
    FETCH_COLLECTIONNAMES_FAIL = 'FETCH_COLLECTIONNAMES_FAIL',

    // Collection Profiles
    FETCH_COLLECTIONPROFILES_START = 'FETCH_COLLECTIONPROFILES_START',
    FETCH_COLLECTIONPROFILES_SUCCESS = 'FETCH__COLLECTIONPROFILES_SUCCESS',
    FETCH_COLLECTIONPROFILES_FAIL = 'FETCH_COLLECTIONPROFILES_FAIL'

;
